import { Document, Page, Text, View, StyleSheet } from "@react-pdf/renderer";
import { format } from "date-fns";

import type { ExportColumn, ExportMeta } from "./types";

const styles = StyleSheet.create({
  page: { padding: 32, fontSize: 9, fontFamily: "Helvetica" },
  headerRow: { flexDirection: "row", justifyContent: "space-between", marginBottom: 10 },
  companyName: { fontSize: 15, fontWeight: 700 },
  muted: { color: "#666666" },
  reportTitle: { fontSize: 12, fontWeight: 700, marginTop: 8 },
  divider: { borderBottomWidth: 1, borderBottomColor: "#e5e5e5", marginVertical: 8 },
  summaryRow: { flexDirection: "row", flexWrap: "wrap", marginBottom: 10, gap: 16 },
  summaryItem: { marginRight: 16, marginBottom: 4 },
  summaryLabel: { color: "#666666", fontSize: 8 },
  summaryValue: { fontSize: 11, fontWeight: 700 },
  tableHeader: {
    flexDirection: "row",
    backgroundColor: "#1e293b",
    paddingVertical: 4,
    paddingHorizontal: 4,
  },
  tableHeaderCell: { color: "#ffffff", fontWeight: 700, fontSize: 8 },
  tableRow: {
    flexDirection: "row",
    paddingVertical: 3,
    paddingHorizontal: 4,
    borderBottomWidth: 0.5,
    borderBottomColor: "#eeeeee",
  },
  tableCell: { fontSize: 8 },
  footer: {
    position: "absolute",
    bottom: 16,
    left: 32,
    right: 32,
    flexDirection: "row",
    justifyContent: "space-between",
    fontSize: 7,
    color: "#999999",
  },
});

/**
 * PDF quality bar (§11): Octaflame header, period label, generated-by and
 * timestamp, summary table, data table. One reusable document for every
 * preset report — charts are out of scope for the MVP export set (§19
 * excludes advanced analytics visuals; the dashboards cover charts live).
 */
export function ReportDocument<T>({
  columns,
  rows,
  meta,
}: {
  columns: ExportColumn<T>[];
  rows: T[];
  meta: ExportMeta;
}) {
  const widthPct = 100 / columns.length;

  return (
    <Document title={meta.title}>
      <Page size="A4" orientation="landscape" style={styles.page} wrap>
        <View style={styles.headerRow} fixed>
          <View>
            <Text style={styles.companyName}>Octaflame</Text>
            <Text style={styles.muted}>Fiesta Gas Distributor — Sorsogon</Text>
          </View>
          <View style={{ alignItems: "flex-end" }}>
            <Text>{meta.periodLabel}</Text>
            <Text style={styles.muted}>
              Generated by {meta.generatedBy} · {format(meta.generatedAt, "MMM d, yyyy h:mm a")}
            </Text>
          </View>
        </View>

        <Text style={styles.reportTitle}>{meta.title}</Text>
        <View style={styles.divider} />

        {meta.summary ? (
          <View style={styles.summaryRow}>
            {Object.entries(meta.summary).map(([label, value]) => (
              <View key={label} style={styles.summaryItem}>
                <Text style={styles.summaryLabel}>{label}</Text>
                <Text style={styles.summaryValue}>{String(value)}</Text>
              </View>
            ))}
          </View>
        ) : null}

        <View style={styles.tableHeader} fixed>
          {columns.map((c) => (
            <Text key={c.key} style={[styles.tableHeaderCell, { width: `${widthPct}%`, textAlign: c.align ?? "left" }]}>
              {c.header}
            </Text>
          ))}
        </View>
        {rows.map((row, i) => (
          <View key={i} style={styles.tableRow} wrap={false}>
            {columns.map((c) => (
              <Text key={c.key} style={[styles.tableCell, { width: `${widthPct}%`, textAlign: c.align ?? "left" }]}>
                {String(c.value(row))}
              </Text>
            ))}
          </View>
        ))}

        <View style={styles.footer} fixed>
          <Text>octaflame_{meta.title.toLowerCase().replace(/\s+/g, "_")}</Text>
          <Text render={({ pageNumber, totalPages }) => `Page ${pageNumber} of ${totalPages}`} />
        </View>
      </Page>
    </Document>
  );
}
