import { format } from "date-fns";

import type { ExportColumn, ExportMeta } from "./types";

function escapeHtml(value: string): string {
  return value
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;");
}

/**
 * Legacy "XLS" export (§11's fourth format). ExcelJS and every maintained
 * npm library only write the modern XLSX (OOXML) format — nothing in the
 * dependency-free budget here can emit real BIFF8 .xls. The long-standing,
 * widely-used workaround is an HTML table served with a .xls extension and
 * an Excel MIME type: Excel opens it natively (with a benign "format
 * doesn't match extension" warning it can dismiss), which is the same
 * trade-off most web apps that still offer "Export to Excel 97-2003" make.
 */
export function buildXlsHtml<T>(rows: T[], columns: ExportColumn<T>[], meta: ExportMeta): string {
  const headerCells = columns
    .map((c) => `<th style="background:#1e293b;color:#fff;padding:4px 8px;">${escapeHtml(c.header)}</th>`)
    .join("");
  const bodyRows = rows
    .map(
      (row) =>
        `<tr>${columns
          .map(
            (c) =>
              `<td style="padding:3px 8px;${c.align === "right" ? "text-align:right;" : ""}">${escapeHtml(
                String(c.value(row))
              )}</td>`
          )
          .join("")}</tr>`
    )
    .join("");

  return `<!doctype html>
<html>
<head><meta charset="utf-8" /></head>
<body>
  <p><b>Octaflame</b> — Fiesta Gas Distributor, Sorsogon</p>
  <p>${escapeHtml(meta.title)} · ${escapeHtml(meta.periodLabel)}</p>
  <p style="color:#666;">Generated by ${escapeHtml(meta.generatedBy)} on ${format(meta.generatedAt, "MMM d, yyyy h:mm a")}</p>
  <table border="1" cellspacing="0" cellpadding="0">
    <thead><tr>${headerCells}</tr></thead>
    <tbody>${bodyRows}</tbody>
  </table>
</body>
</html>`;
}
