import ExcelJS from "exceljs";
import { format } from "date-fns";

import type { ExportColumn, ExportMeta } from "./types";

const HEADER_FILL: ExcelJS.Fill = {
  type: "pattern",
  pattern: "solid",
  fgColor: { argb: "FF1E293B" },
};

/**
 * XLSX quality bar (§11): styled header row, frozen panes, column widths,
 * currency/number formats, and a summary sheet — built to look like it came
 * from a real company, since this is what gets emailed to Fiesta Gas.
 */
export async function buildXlsx<T>(
  rows: T[],
  columns: ExportColumn<T>[],
  meta: ExportMeta
): Promise<Buffer> {
  const workbook = new ExcelJS.Workbook();
  workbook.creator = "Octaflame OS";
  workbook.created = meta.generatedAt;

  const summarySheet = workbook.addWorksheet("Summary");
  summarySheet.columns = [{ width: 28 }, { width: 44 }];
  summarySheet.addRow(["Octaflame", "Fiesta Gas Distributor — Sorsogon"]).font = { bold: true, size: 14 };
  summarySheet.addRow([meta.title]).font = { bold: true, size: 12 };
  summarySheet.addRow([]);
  summarySheet.addRow(["Period", meta.periodLabel]);
  summarySheet.addRow(["Generated by", meta.generatedBy]);
  summarySheet.addRow(["Generated at", format(meta.generatedAt, "MMM d, yyyy h:mm a")]);
  summarySheet.addRow(["Rows", rows.length]);
  if (meta.summary) {
    summarySheet.addRow([]);
    for (const [key, value] of Object.entries(meta.summary)) {
      summarySheet.addRow([key, value]);
    }
  }
  summarySheet.getColumn(1).font = { bold: true };

  const dataSheet = workbook.addWorksheet(meta.title.slice(0, 31) || "Data", {
    views: [{ state: "frozen", ySplit: 1 }],
  });

  dataSheet.columns = columns.map((c) => ({
    header: c.header,
    key: c.key,
    width: Math.max(c.header.length + 4, 12),
    style: c.numFmt ? { numFmt: c.numFmt } : undefined,
  }));

  const headerRow = dataSheet.getRow(1);
  headerRow.eachCell((cell) => {
    cell.font = { bold: true, color: { argb: "FFFFFFFF" } };
    cell.fill = HEADER_FILL;
    cell.alignment = { vertical: "middle" };
  });

  for (const row of rows) {
    dataSheet.addRow(Object.fromEntries(columns.map((c) => [c.key, c.value(row)])));
  }

  columns.forEach((c, i) => {
    if (c.align === "right") {
      dataSheet.getColumn(i + 1).alignment = { horizontal: "right" };
    }
  });

  const buffer = await workbook.xlsx.writeBuffer();
  return Buffer.from(buffer);
}
